-- "Users can update their own subscription SOS usage" restricts WHICH ROW
-- can be updated (user_id = auth.uid()) but Postgres RLS has no way to
-- restrict WHICH COLUMNS a USING/WITH CHECK policy applies to — so this
-- policy actually let any authenticated user update EVERY column of their
-- own subscribers row, including subscription_tier, subscribed,
-- sos_used_this_month, appointments_used_this_month, etc. A patient could
-- grant themselves a free Premium subscription (unlimited SOS + paid
-- appointment scheduling) and reset their own monthly quotas at will,
-- entirely bypassing Stripe, just by calling the normal Supabase client
-- directly (no edge function needed).
--
-- No legitimate code path needs this: every real write to subscribers
-- already goes through an edge function using the service-role client
-- (check-subscription, cancel-subscription, mark-sos-used, appointments),
-- which bypasses RLS regardless of this policy's existence — grep over
-- src/ confirms the frontend never calls
-- supabase.from('subscribers').update(...) directly. Removing this policy
-- closes the bypass with zero functional impact.
DROP POLICY IF EXISTS "Users can update their own subscription SOS usage" ON public.subscribers;
